version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    working_dir: /var/www
    volumes:
      - ./php:/var/www
      - ./nginx/conf:/etc/nginx/conf.d