version: "3.9"
services:
  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./php:/usr/share/nginx/html
