services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - ./cert:/cert

    webserver1:
      image: php:apache
      ports:
        - 81:80
      volumes:
        - ../ulideserver:/var/www/html

    webserver2:
      image: php:apache
      ports:
        - 82:80
      volumes:
        - ../ulideserver:/var/www/html